export const BUSINESS = {
  companyName: 'Sudofim Serv SRL',
  shortName: 'Sudofim Serv',
  salesPhone1: '0721426487',
  salesPhone1Intl: '+40721426487',
  salesPhone1Name: 'Bogdan Chritofor',
  salesPhone1Role: 'Vanzari',
  salesPhone2: '0723968887',
  salesPhone2Intl: '+40723968887',
  salesPhone2Name: 'Bogdan Adrian',
  salesPhone2Role: 'Administrator',
  email: 'sudofim2006@gmail.com',
  city: 'Ploiesti',
  county: 'Prahova',
  country: 'Romania',
  url: 'https://sudofimserv.ro',
  foundingYear: '2006',
  description: 'Solutii complete pentru sudura si echipamente industriale - vanzare, inchiriere, service.',
} as const;

export const CATEGORIES_ORDER = [
  'Aparate Sudura',
  'Sudura Electrofuziune',
  'Sudura Cap la Cap',
  'Generatoare de Curent',
  'Compactoare',
  'Compresoare',
  'Pompe',
  'Masini de Taiat',
  'Fierastraie',
  'Excavatoare',
  'Utilaje Curatenie',
  'Alte Echipamente',
] as const;
